export const CREATE_AFFILIATION = "CREATE_AFFILIATION";
export const RETRIEVE_AFFILIATIONS = "RETRIEVE_AFFILIATIONS";
export const UPDATE_AFFILIATION = "UPDATE_AFFILIATION";
export const DELETE_AFFILIATION = "DELETE_AFFILIATION";
export const DELETE_ALL_AFFILIATIONS = "DELETE_ALL_AFFILIATIONS";
export const RETRIEVE_TOTALS = "RETRIEVE_TOTALS";
export const RETRIEVE_TOPICS = "RETRIEVE_TOPICS";
export const RETRIEVE_DATASETS = "RETRIEVE_DATASETS";